@startuml
actor ユーザ
boundary ブラウザ
control web.php
control Jisyu3_1Controller
boundary input.blade.php
boundary output.blade.php

ユーザ -> ブラウザ:該当ページをリクエスト[/Jisyu3]
ブラウザ -> web.php: GET[/jisyu3]
web.php -> Jisyu3_1Controller:@index
Jisyu3_1Controller -> input.blade.php

ユーザ->input.blade.php:送信ボタンを押下
input.blade.php->web.php:POST
web.php->Jisyu3_1Controller:@post
Jisyu3_1Controller->output.blade.php
@enduml